name = "wordle-bot"
main = "src/index.js"
compatibility_date = "2022-06-18"
node_compat = true

[[ d1_databases ]]
binding = "BOT_DB"
database_name = "wordl-bot-db"
database_id = "c283f8ba-8f9a-493c-bb45-0daf6102ef64"