DROP TABLE IF EXISTS  Submissions;

DROP TABLE IF EXISTS Users;

CREATE TABLE Users(
    UserID INTEGER NOT NULL UNIQUE,
    Score INTEGER NOT NULL
);

CREATE TABLE Submissions(
    SubmissionID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,    
    UserID INTEGER NOT NULL,
    Attempts  INTEGER NOT NULL,
    WordleDay INTEGER NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    CONSTRAINT UNIQUE_DAY UNIQUE (UserID, WordleDay)
);
